### ISSUE TITLE
City search gives no results for exact match

### ISSUE THREAD

**Issue by fungjj92** [azavea/climate-change-lab#101]
Repost from CC-API #108, https://github.com/azavea/climate-change-api/issues/108

City search gives a dropdown of cities that contain a substring of the search text:
![screen shot 2016-09-30 at 9 24 00 am](https://cloud.githubusercontent.com/assets/1032849/18993103/a9661aa4-86ef-11e6-953f-9334dce8e4de.png)

And works if the user searches for most of the city name:
![screen shot 2016-09-30 at 9 22 09 am](https://cloud.githubusercontent.com/assets/1032849/18993112/b2e5b594-86ef-11e6-8b7d-0c2168c3c3db.png)

But if the user types in the full name too quickly, it implies that the city is not in our database:
![screen shot 2016-09-30 at 9 22 17 am](https://cloud.githubusercontent.com/assets/1032849/18993128/c1234ef0-86ef-11e6-9aa4-a5a056f616d2.png)

I'm putting this in the API project since this appears to be caused by the `?search=` giving no responses:
```
GET /api/city/?search=philadelphia,%20pa
{"type":"FeatureCollection","count":0,"next":null,"previous":null,"features":[]}
```

**Comment by fungjj92** [comment]
The problem is actually that the regex is for text blocks in City name only. 

Houston, T works because T is in Houston.
Houston, TO works because TO is in Houston.
Houston, TX doesn't because TX is not in Houston.

**Comment by KlaasH** [comment]
Lab/API separation not always clear.  Sending this one back to API (https://github.com/azavea/climate-change-api/issues/108).
