### ISSUE TITLE
Indicator parameter customization

### ISSUE THREAD

**Issue by rmartz** [azavea/climate-change-lab#120]
A growing number of indicators in the API support custom parameters, such as the Degree Day indicators that allow the user to specify their own base temperature to compare from. We should extend the lab to allow the user to specify their own value for these when appropriate. This can also be used for cross-indicator features such as to specify the desired output units.

This depends on the API exposing which indicators use which parameters, which is intended to be implemented as part of azavea/climate-change-api#148

**Comment by flibbertigibbet** [comment]
Carded as #182
