### ISSUE TITLE
Update staging API configuration

### ISSUE THREAD

**Issue by rmartz** [azavea/climate-change-lab#132]
The DNS for the API's staging instance has changed from `staging.api.futurefeelslike.com` to `api.staging.futurefeelslike.com` - we should update the lab's configuration the match the new location.

**Comment by rmartz** [comment]
@fungjj92 This is good now with #133, right?

**Comment by fungjj92** [comment]
it was part of it but more importantly this has been fixed by changing the config in jenkins
