### ISSUE TITLE
Handle threshold indicators

### ISSUE THREAD

**Issue by fungjj92** [azavea/climate-change-lab#141]
They don't currently get graphed, since they take an extra parameter

Either handle graphing them, or filter them out of the indicator list.

I vote, for now, filter them out until or unless we decide to put effort into lab

**Comment by CloudNiner** [comment]
I _think_ this is a specific case of #120?

**Comment by fungjj92** [comment]
Yes but a temporary coverup for very broken indicator graphs if you planned on showing the lab at AWRA. This coverup would only be until #120 is addressed
