### ISSUE TITLE
Jenkins should only deploy to production lab site on changes to master branch

### ISSUE THREAD

**Issue by CloudNiner** [azavea/climate-change-lab#151]
Currently deploys on all changes to develop.

**Comment by flibbertigibbet** [comment]
Update: only deploys to staging, only on changes to `develop` branch.

**Comment by flibbertigibbet** [comment]
Switch to Jenkins pipeline, to run linting and tests only on PR branches, update GitHub status, and only deploy (to appropriate environment) for `develop` and `master`. Related to #148.
