### ISSUE TITLE
Incorrect API host reference from CI deployment

### ISSUE THREAD

**Issue by fungjj92** [azavea/climate-change-lab#165]
In the console, tries to POST to:
"https://lab.climate.azavea.com/$%7Benv.API_HOST%7D/api-token-auth/"

Requires more investigation but looks suspiciously related to references here:
https://github.com/azavea/climate-change-lab/pull/160/files#diff-58231b16fdee45a03a4ee3cf94a9f2c3R24

**Comment by flibbertigibbet** [comment]
Gradle syntax requires outer string quotation to be double and not single quotes for variable substitution to work, as became apparent with the `writeFile` block below, although documentation is not clear on this.

**Comment by fungjj92** [comment]
Nice
