### ISSUE TITLE
Implement time slider

### ISSUE THREAD

**Issue by CloudNiner** [azavea/climate-change-lab#176]
Time slider defaults to full year range 1950-2100.

To start, only update the chart when the user stops dragging on one of the two ticks of the slider.
![screen shot 2017-07-26 at 12 46 56](https://user-images.githubusercontent.com/1818302/28633082-8a0077c0-7200-11e7-8b5e-89a931d1c000.png)

**Comment by fungjj92** [comment]
Are we imagining the time slider is maintained globally (like scenario, models, city) or gets reset/refreshed when a new indicator is selected? @jfrankl

**Comment by jfrankl** [comment]
Please have it get reset/refreshed when a new indicator is selected.

**Comment by fungjj92** [comment]
Thanks!
