### ISSUE TITLE
Add legend to indicator chart

### ISSUE THREAD

**Issue by CloudNiner** [azavea/climate-change-lab#177]
In screenshot below, green line is average of selected models

In screenshot below, grey box/area on chart is the range between min/max of the selected models

![screen shot 2017-07-26 at 12 48 43](https://user-images.githubusercontent.com/1818302/28633130-c8497360-7200-11e7-8622-8c0e835a0b6c.png)

**Comment by jcahail** [comment]
Attempt to style legend boxes appropriately.
