### ISSUE TITLE
Add text area below indicator chart to describe chart sources

### ISSUE THREAD

**Issue by CloudNiner** [azavea/climate-change-lab#178]
For now, this can just contain placeholder text.

![screen shot 2017-07-26 at 12 49 18](https://user-images.githubusercontent.com/1818302/28633157-e0b77758-7200-11e7-8674-4ab56cd25af3.png)

**Comment by jcahail** [comment]
I suggest something like, "Derived from the Global Daily Downscaled Projections (NEX-GDDP) and the Coupled Model Intercomparison Project Phase 5 (CMIP5)."
