### ISSUE TITLE
Implement "Get API Call" button + dialog

### ISSUE THREAD

**Issue by CloudNiner** [azavea/climate-change-lab#181]
Dialog should contain:
- text box that shows the `curl` command that could be used to request the data used for the current chart state, and should update as the user changes options
- a button to the right of the text box that the user can click to copy the contents of the text box to their system clipboard

![screen shot 2017-07-26 at 12 54 59](https://user-images.githubusercontent.com/1818302/28633393-a8065432-7201-11e7-8034-39f2dc7dd835.png)

**Comment by flibbertigibbet** [comment]
Is this the text actually intended to be displayed in the pop-up box?

**Comment by CloudNiner** [comment]
That seems like design placeholder text. @jcahail do you have preferred text for this?

**Comment by jcahail** [comment]
How about, "Use our API to access these data regularly for your own research or application."?

**Comment by flibbertigibbet** [comment]
Went digging for an appropriate clipboard-like icon under `src/assets/fonts/fontello/css/mantle.css`, but didn't see any.

Could someone in design help me out with that one? Otherwise I might go with the umbrella icon that we do have. :smile:
