### ISSUE TITLE
Implement component and templates for indicator-specific parameters

### ISSUE THREAD

**Issue by CloudNiner** [azavea/climate-change-lab#182]
An example of what this looks like:

![screen shot 2017-07-26 at 12 57 36](https://user-images.githubusercontent.com/1818302/28633503-05a73e80-7202-11e7-8988-6633bf3a0ba5.png)

Things to consider:
- Some indicators have parameters without defaults. For the lab, we can either choose arbtrary defaults or delay indicator chart load until a value is entered for these parameters
- Indicators have variable numbers of custom parameters
- A template will need to be written and added to the project for each indicator with extra parameters

**Comment by CloudNiner** [comment]
Work with @jcahail and @fungjj92 or @CloudNiner to develop the templates for each indicator that needs one.

**Comment by flibbertigibbet** [comment]
Regarding the example image: for the cooling degree days parameter, there is no `threshold_comparator` parameter, so there's no option for which "less than" is a choice; as I understand it, the results will always be for temperatures less than the `basetemp` parameter.

There are a number of other parameters not reflected in the example. In particular, I don't think `agg`, `custom_time_agg`, `years`, or `time_aggregation` are user-controllable elsewhere, but it may not make sense to throw them all in this new component. Do we have some more information on what, exactly, we'd like to control for each indicator?

**Comment by CloudNiner** [comment]
Yes, design was unaware of the specifics for the Cooling Degree Days parameter, for a more helpful, complete example, change the title "Cooling Degree Days" in the example image to "Min Temperature Threshold". That indicator should align with the extra "indicator-specific" parameters available on the `min_temperature_threshold` indicator.

These templates would not include any parameters that are globally available on all indicators. This effectively means ignoring including in the template any parameter that is defined as part of [IndicatorParams](https://github.com/azavea/climate-change-api/blob/develop/django/climate_change_api/indicators/params.py#L131).

An easy way to get started might be to develop a template for each IndicatorParams subclass as those are the parameters that are "extra" and only apply to certain indicators.

**Comment by flibbertigibbet** [comment]
Okay. Regarding `time_aggregation`, that looks to be globally available but with options dependent on the indicator. Currently there's a TODO in `chart.components.ts` to make it user-selectable (currently defaults to first option). Should that be part of this component?

**Comment by flibbertigibbet** [comment]
Mapping of indicator parameters to the indicators that use them, for those that are not used by all indicators, based on results of `/api/indicators` self-describing endpoint:

```
{'basetemp': ['cooling_degree_days', 'heating_degree_days'],
 'basetemp_units': ['cooling_degree_days', 'heating_degree_days'],
 'historic_range': ['extreme_cold_events',
  'extreme_heat_events',
  'extreme_precipitation_events',
  'heat_wave_duration_index',
  'heat_wave_incidents'],
 'percentile': ['extreme_cold_events',
  'extreme_heat_events',
  'extreme_precipitation_events',
  'percentile_high_temperature',
  'percentile_low_temperature',
  'percentile_precipitation'],
 'threshold': ['max_temperature_threshold',
  'min_temperature_threshold',
  'precipitation_threshold'],
 'threshold_comparator': ['max_temperature_threshold',
  'min_temperature_threshold',
  'precipitation_threshold'],
 'threshold_units': ['max_temperature_threshold',
  'min_temperature_threshold',
  'precipitation_threshold']}
```

**Comment by CloudNiner** [comment]
Nice. That seems correct. 

`time_aggregation` should not be a part of the templates. We're only using `yearly` for now. It's probably worth exploring how to fit that parameter in at a later time.

**Comment by flibbertigibbet** [comment]
Thinking about how to break this task down some more, here's a proposal:

We could make four control components for the inputs (dropdowns and text entry fields) and five templates for the variations on combinations of those four inputs, and then a mapping of each of the 13 indicators taking additional parameters (out of 23 total) to their template, plus a custom display string.

The input components would be:
 - units dropdown, for `basetemp_units` and `threshold_units`, hopefully can also be generalized to replace existing display units dropdown in header; options hard-coded with descriptors
 - comparator dropdown, also with hard-coded options, for use by `threshold_comparator`
 - simple numeric field with no range check, for use by `historic_range` (a year), `basetemp`, and `threshold`
 - numeric field with 0 to 100 range check for `percentile`

The templates would be:
 - using `basetemp` and `basetemp_units` (`cooling_degree_days` and `heating_degree_days`)
 - using just `historic_range`
 - using just `percentile`
 - using both `historic_range` and `percentile`
 - for the three `threshold` indicators

**Comment by fungjj92** [comment]
That looks super sensible to me. I think a fair amount of this could be worked on simultaneously, which is a plus!

**Comment by flibbertigibbet** [comment]
Another idea suggested by @CloudNiner would be to map templates directly to indicators, which would save overhead of nesting components inside components, but would mean input components could not be generalized out separately (must be inlined), so might be more boilerplate.

**Comment by CloudNiner** [comment]
Yeah I think stick with your initial strategy, we can always re-evaluate if something goes wonky or there's an implementation hiccup. As discussed yesterday, go ahead and add separate issues for however you want to split this up and we'll add them to this sprint.

**Comment by flibbertigibbet** [comment]
Went with creating five issues for the five additional input parameter combinations.

Maybe we should mark the other issues as blocked until the first one gets done, as the first one would set up the template structure.
