### ISSUE TITLE
Update JSON export /  API calls button to include historical request

### ISSUE THREAD

**Issue by CloudNiner** [azavea/climate-change-lab#194]
Now that the scenario selector only allows the choice of the future scenarios, and historical data is always included in the chart, the "Download the data for this chart" operation and the API `curl` call no longer match all of the data in the chart, since the chart includes both historical and future data, and the JSON download/`curl` components only make the future data available. 

We should refactor the JSON download/`curl` components in some way such that the user understands that the two datasets require two different queries, and make them both available for `curl` and download.

**Comment by flibbertigibbet** [comment]
Needs design input on how that should work

**Comment by jfrankl** [comment]
Happy to work with you on this. Are you imagining an interface like this where the user can toggle between future and historical output on the API call?

![image](https://user-images.githubusercontent.com/1809908/29192041-d803665a-7ded-11e7-8169-9bf33164c577.png)

Or exposing both all the time?

![image](https://user-images.githubusercontent.com/1809908/29192051-dec69ac0-7ded-11e7-9718-1d2204c0b074.png)

Or am I way off?

**Comment by flibbertigibbet** [comment]
Thanks @jfrankl! Personally I like the first option.

**Comment by CloudNiner** [comment]
I think either of those will work, I would be cautious to ensure that its clear which data is selected if we go with the first option. Maybe the buttons get more traditional tab borders so that the button is visually grouped with the copyable text?

**Comment by fungjj92** [comment]
@jfrankl Thoughts on Andrew's comment?

**Comment by fungjj92** [comment]
Kind of like this? http://valor-software.com/ngx-bootstrap/#/tabs#manual

**Comment by jfrankl** [comment]
Let's do the second option where we expose both links.
