### ISSUE TITLE
Units dropdown does not display default

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/climate-change-lab#196]
The units dropdown component added in #192 is empty until the user explicitly selects a unit. The default unit should display when there is no user selection.

![image](https://user-images.githubusercontent.com/960264/29088786-44673fa8-7c48-11e7-96a2-f65392ad2480.png)

**Comment by CloudNiner** [comment]
Confirm only reproduceable on old projects. If so can be closed.

**Comment by CloudNiner** [comment]
Can only reproduce on old projects on current develop, and as soon as an indicator is selected, the default shows for all subsequent indicators for that project. Closing.
