### ISSUE TITLE
Clean up double caret on units dropdown

### ISSUE THREAD

**Issue by fungjj92** [azavea/climate-change-lab#200]

**Comment by flibbertigibbet** [comment]
related to #196?

**Comment by fungjj92** [comment]
<img width="103" alt="screen shot 2017-08-09 at 3 58 52 pm" src="https://user-images.githubusercontent.com/10568752/29141313-b3fce6aa-7d1b-11e7-81e0-fae323a8b044.png">

It's always there 🐰

**Comment by flibbertigibbet** [comment]
Oh, the second caret? Got it. :mag:
