### ISSUE TITLE
Refactor chart removal

### ISSUE THREAD

**Issue by fungjj92** [azavea/climate-change-lab#213]
Chart removal is a little messy. Several chart-related settings have been added and are force- removed/reset alongside charts. If possible, refactor charts such that all its associated settings are contained on the chart so removal will reset all associated settings

Run into especially with #210

**Comment by flibbertigibbet** [comment]
In particular, would be helpful if chart removal would actually destroy the component. Otherwise lifecycle events that form components depend on won't fire if, for example, the same indicator is re-selected (currently handled by ignoring).
