### ISSUE TITLE
Navbar changes incompatible with threshold indicators

### ISSUE THREAD

**Issue by fungjj92** [azavea/climate-change-lab#217]
Changes to the nav bar options (model, scenario etc) don't propagate threshold indicator options in the request because they are captured from threshold option change events, and aren't saved on the chart. The produces an incomplete request and infinite chart load.

See line: https://github.com/azavea/climate-change-lab/pull/210/files#diff-d713ba72d21e2173ab63fddb34fd01e9R114

**Comment by jcahail** [comment]
May be fixed by #209.
