### ISSUE TITLE
Flashing view in new/edit project modal

### ISSUE THREAD

**Issue by fungjj92** [azavea/climate-change-lab#227]
![edit-project-cclab](https://user-images.githubusercontent.com/10568752/29926965-e695daf4-8e32-11e7-92d2-0af6e6d4ade2.gif)

See #221

**Comment by maurizi** [comment]
We removed the edit project link in https://github.com/azavea/climate-change-lab/commit/f5a6bffbecff9a63b867e680dfdae6c13d117cc3#diff-017b6e710461134e5b4c9fd34aeabe7c, so I think we can close this as a non-issue now.
