### ISSUE TITLE
Extra parameters controls cut off

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/climate-change-lab#234]
![image](https://user-images.githubusercontent.com/960264/29974494-50c74bdc-8f33-11e7-8093-951658c185fa.png)

**Comment by CloudNiner** [comment]
I don't see this issue on staging in the Chrome browser.

<img width="681" alt="screen shot 2017-09-06 at 10 13 30" src="https://user-images.githubusercontent.com/1818302/30116637-18a1dc24-92ec-11e7-9ecc-dadf20e9e1b0.png">


Any additional conditions to reproduce?

**Comment by flibbertigibbet** [comment]
It may be related to screen height. Maybe try with the console window open?

**Comment by flibbertigibbet** [comment]
I'm seeing this on staging with the console closed, on Chrome Linux with a 13" screen.

**Comment by CloudNiner** [comment]
What's the browser window height and width? I don't see it even if I make the browser window very small, e.g. 600x400px.

**Comment by flibbertigibbet** [comment]
Playing with the browser resizer, the controls don't seem to change with the screen size. Maybe worth testing in BrowserStack.

**Comment by flibbertigibbet** [comment]
Firefox (same system):

![image](https://user-images.githubusercontent.com/960264/30118398-3996066c-9323-11e7-9cc2-46a6e3c6cbc6.png)

**Comment by flibbertigibbet** [comment]
On BrowserStack, Mac Sierra/Chrome looks fine, but Windows 10/Chrome has the issue:

![image](https://user-images.githubusercontent.com/960264/30119241-705fbdd0-9325-11e7-9296-ba8aaaec868a.png)

**Comment by flibbertigibbet** [comment]
BrowserStack Windows 10/Firefox:

![image](https://user-images.githubusercontent.com/960264/30119335-a96db226-9325-11e7-921a-628cb67553b6.png)
