### ISSUE TITLE
New project creation fails

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/climate-change-lab#245]
New project creation fails due to the two new project properties added [here](https://github.com/azavea/climate-change-api/pull/649) not existing.

Add `visibility` and `allModels` properties to new project creation POST so request succeeds.

**Comment by CloudNiner** [comment]
This was addressed by deploying the latest develop to staging, which hadnt occurred since August 28 due to an issue with the AWS CLI version reverting on the build host.
