### ISSUE TITLE
Component to combine historic and percentage controls

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/climate-change-lab#247]
Add component for controls for the two indicators that use both historic range and percentage optional parameters.

See #246.

**Comment by rmartz** [comment]
The two cases are Extreme Precipitation Events and Extreme Heat Events:
<img width="525" alt="screen shot 2017-09-07 at 12 47 23 pm" src="https://user-images.githubusercontent.com/1032849/30174917-b25fa3c6-93ca-11e7-9844-eb5e55239e68.png">

**Comment by flibbertigibbet** [comment]
See #256 for styling notes.

**Comment by CloudNiner** [comment]
Text should be:

“Show extreme heat events at percentile [____] with historic range base year [____]”
