### ISSUE TITLE
Display error message if user types in invalid city name 

### ISSUE THREAD

**Issue by jcahail** [azavea/climate-change-lab#251]
Right now the only indication that a user will get that we don't have data loaded for a particular city is that the "Create Project" button remains grayed out: 

![image](https://user-images.githubusercontent.com/24727081/30180284-5cf42d04-93dd-11e7-9e13-0e25a921cc7f.png)

**Comment by jcahail** [comment]
^^ that did say "Old Bridge, NJ" (which is an actual place) in the choose a city field

**Comment by flibbertigibbet** [comment]
Styling related to #243

**Comment by jcahail** [comment]
Blocked by #266.
