### ISSUE TITLE
Extreme heat events parameters

### ISSUE THREAD

**Issue by jfrankl** [azavea/climate-change-lab#256]
Please turn parameters into a single sentence instead of two:

"Show extreme heat events at percentile [dropdown] of projections with historic base year [dropdown]"

We might want to edit this to make it shorter.

![image](https://user-images.githubusercontent.com/1809908/30295173-b103e58c-970d-11e7-9a84-be8db1a65bfb.png)

**Comment by flibbertigibbet** [comment]
Duplicate of #247.
