### ISSUE TITLE
Model selector should only show models valid for the current dataset

### ISSUE THREAD

**Issue by CloudNiner** [azavea/climate-change-lab#257]
Currently it shows all models from `/api/climate-model/` but should actually show the model list from the selected dataset using `/api/dataset/` instead:

![screen shot 2017-09-18 at 15 19 36](https://user-images.githubusercontent.com/1818302/30560203-241bb2bc-9c85-11e7-9b30-b6c10a702ec7.png)

**Comment by flibbertigibbet** [comment]
Depends on #258
