### ISSUE TITLE
Restyle model selector

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/climate-change-lab#268]
Currently it is a modal that displays all possible models from all datasets, with options unavailable for the currently selected dataset disabled. Default styling for the disabled control is to grey out the checkbox.

The decision was made to continue listing all models but grey out unavailable options, as the user may have made model selections, then toggled datasets, but would like to keep selected models not available for the new dataset.

The number of models is large enough that a different form of control that is easier to read may be an improvement, or at least some change of styling to the existing modal controls.

See #258.

**Comment by jfrankl** [comment]
Let me know what you think of this idea.

![image](https://user-images.githubusercontent.com/1809908/32077234-afad4986-ba70-11e7-85e0-a77aaa6fe933.png)

* Switch to three columns so the list doesn't go so far down the page
* Hide models that are not accessible. User can click button to expand and see the extra models, which are disabled. The label/copy needs work
* Some other minor style touchups

Here's what it would look like with the disabled models expanded:

![image](https://user-images.githubusercontent.com/1809908/32077398-4a40cf72-ba71-11e7-89ff-eff00c66204c.png)

**Comment by jfrankl** [comment]
I spoke with @fungjj92 about this feature. In the future, we think it might be helpful to recommend models to the user or provide more information that would help users pick which models are important to them. That kind of functionality could be valuable and should be considered for Temperate. We felt that level of enhance was out of scope for this Lab task.

**Comment by CloudNiner** [comment]
Agreed, looks good, seems like a solid middle ground for now. 

If we were to recommend models based on location, that would be a feature in some farther off world and would be more useful to focus on in Temperate as you suggest.

**Comment by fungjj92** [comment]
Stellar! I like the organization and clarity much better.
