### ISSUE TITLE
Change precipitation threshold units to rates

### ISSUE THREAD

**Issue by rmartz** [azavea/climate-change-lab#276]
In https://github.com/azavea/climate-change-api/issues/664 we changed the API to use precipitation as a rate for Precipitation Threshold as well as Percentile Precipitation. Percentile Precipitation is able to ingest the new changes dynamically, but Precipitation Threshold needs to be updated to reflect the new options for `comparator_units`. They can be one of:
- `kg/m^2/s`
- `in/day`
- `mm/day`

These better reflect the difference in scale (Previously all were raw units like `kg/m^2` and `in`, which caused them to all be invisibly handled internally as `(unit)/s`.

**Comment by flibbertigibbet** [comment]
Note that it's necessary to keep the available query units hard-coded in the lab because they are not programmatically discoverable from the `indicators` endpoint, as the display units are.
