### ISSUE TITLE
Display user first & last instead of email in header

### ISSUE THREAD

**Issue by fungjj92** [azavea/climate-change-lab#278]
Current lab:
![screen shot 2017-10-06 at 2 40 45 pm](https://user-images.githubusercontent.com/10568752/31293217-751e81da-aaa4-11e7-9b82-12df2d130733.png)

Update to reflect:
![screen shot 2017-10-06 at 2 40 49 pm](https://user-images.githubusercontent.com/10568752/31293211-7211ffa8-aaa4-11e7-963a-2fd822c7a46b.png)

Will probably involve getting user info via auth.service.ts

**Comment by hadleystein1** [comment]
This is a good idea, but it don't think it should prevent us from doing outreach/doing a release.

**Comment by fungjj92** [comment]
API was updated to display email instead of first/last so now they match and this can be closed 🎉
