### ISSUE TITLE
Implement average temperature indicator charts 

### ISSUE THREAD

**Issue by CloudNiner** [azavea/climate-change-lab#28]

**Comment by CloudNiner** [comment]
Depends on #26

**Comment by fungjj92** [comment]
Clarifying -- is this implementing 2 charts: tasmin and tasmax with the avg aggregation applied to each?

**Comment by CloudNiner** [comment]
Yes. It would be implementing the yearly_average_max_temp and yearly_average_min_temp indicators, pulling data from /api/climate-data/:cityid/:scenarioid/indicators/:indicatorname/

**Comment by fungjj92** [comment]
Closed by PR #38
