### ISSUE TITLE
NEX-GDDP legend persists when user selects LOCA

### ISSUE THREAD

**Issue by jcahail** [azavea/climate-change-lab#285]
![image](https://user-images.githubusercontent.com/24727081/31667244-dd8fa476-b31c-11e7-8c4a-ae3e53e62d36.png)

**Comment by CloudNiner** [comment]
@jcahail what text do you want to use for the LOCA version of the legend?

**Comment by jcahail** [comment]
Downscaled from CMIP5, using the Localized Constructed Analogs (LOCA) statistical technique.
Open to other tweaks.

**Comment by CloudNiner** [comment]
Works for me, I might suggest adding a second sentence that reads "Data available at loca.ucsd.edu".

**Comment by CloudNiner** [comment]
That looks like:

![screen shot 2017-10-17 at 09 36 43](https://user-images.githubusercontent.com/1818302/31667912-c2883a6a-b31e-11e7-8134-5fc33eaf27bb.png)

**Comment by jcahail** [comment]
Downscaled from CMIP5, using the Localized Constructed Analogs (LOCA) statistical technique.
