### ISSUE TITLE
Drop down menu displays incorrectly in Firefox

### ISSUE THREAD

**Issue by dboyer** [azavea/climate-change-lab#289]
Tested on production in Firefox on a Mac.

![screen shot 2017-10-24 at 2 40 17 pm](https://user-images.githubusercontent.com/516764/31961672-66488cae-b8c9-11e7-8314-26d3180350c7.png)

**Comment by flibbertigibbet** [comment]
See #234

**Comment by CloudNiner** [comment]
Closing, duplicate of #234
