### ISSUE TITLE
Switch to a Node LTS release.

### ISSUE THREAD

**Issue by maurizi** [azavea/climate-change-lab#291]
We're currently using Node 7 which is not a long-term support release

https://github.com/azavea/climate-change-lab/blob/7e2dc2726f0b6ec68821d9cab005f252fc4a84dd/docker-compose.yml#L8

We should _either_ downgrade this project to Node 6, which is the current LTS release, or upgrade to Node 8, which will be a supported LTS release after 10/31.

**Comment by hectcastro** [comment]
I would prefer `node:6-slim`, unless there is a significant benefit we get from Node 7.

**Comment by CloudNiner** [comment]
Note that [there's an issue](https://github.com/azavea/climate-change-lab/pull/290#issuecomment-339656237) with the development node package link workflow on node 8+, so node 6 is probably better for now.

**Comment by flibbertigibbet** [comment]
Saw the issue with the missing angular cli on v8 but not v6 until I removed a globally installed version of the old angular cli on v6; after that, v8 built fine for me.
 - `sudo npm uninstall -g angular-cli`
 - `sudo npm uninstall -g @angular/cli` (new version)

Note that the CLI currently [supports a minimum node version of 6.9.0](https://github.com/angular/angular-cli#prerequisites), and that there is now a stable v8 release.
