### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/climate-change-lab#295]
Check for newer versions of package dependencies and upgrade if possible.

Things to check include:
  - npm packages for the front end
  - ansible role versions
  - installed system packages, such as node

**Comment by fungjj92** [comment]
Partially or fully completed by #303 ? @flibbertigibbet

**Comment by flibbertigibbet** [comment]
#303 had made a minor version upgrade to Angular and some related packages, but had not updated project dependencies otherwise.

**Comment by maurizi** [comment]
Only update Angular to the latest `4.x` release to avoid needing to update Angular on `climate-change-components` and Temperate.
