### ISSUE TITLE
Center "Update" button in the Select Models box

### ISSUE THREAD

**Issue by jcahail** [azavea/climate-change-lab#297]
![image](https://user-images.githubusercontent.com/24727081/32328612-dbf7d3fe-bfb0-11e7-91fc-ec3a9afc67d0.png)

**Comment by CloudNiner** [comment]
Should this still be done given the changes in #293?

![screen shot 2017-11-02 at 09 40 37](https://user-images.githubusercontent.com/1818302/32329028-22555df2-bfb2-11e7-91f2-b2ab64586dbc.png)

**Comment by CloudNiner** [comment]
Closed, addressed by #293
