### ISSUE TITLE
Use two columns to display models in Select Models 

### ISSUE THREAD

**Issue by jcahail** [azavea/climate-change-lab#298]
![image](https://user-images.githubusercontent.com/24727081/32328838-97f3b5b4-bfb1-11e7-92fe-4508ff030e4e.png)

**Comment by CloudNiner** [comment]
In #293 we switched to a three-column layout. See changes on staging:

![screen shot 2017-11-02 at 09 40 37](https://user-images.githubusercontent.com/1818302/32328972-fc5d1b8a-bfb1-11e7-81d7-15e1d44fdba9.png)

Feel free to close this if the three-column change is acceptable.

**Comment by jcahail** [comment]
Yikes, sorry about that.
