### ISSUE TITLE
Open links to NEX-GDDP and LOCA info pages in new tabs

### ISSUE THREAD

**Issue by jcahail** [azavea/climate-change-lab#299]
Currently directs user to the site, effectively leaving the application

<img width="679" alt="screen shot 2017-11-02 at 10 38 32 am" src="https://user-images.githubusercontent.com/1032849/32331758-1e97666c-bfba-11e7-9a3a-f52323262ebe.png">

<img width="743" alt="screen shot 2017-11-02 at 10 38 39 am" src="https://user-images.githubusercontent.com/1032849/32331761-21b1eade-bfba-11e7-9643-eabf22eb3cca.png">

**Comment by rmartz** [comment]
We should be careful about opening new tabs... there are a variety of arguments against forcing links to do that that generally, though for specific uses it may make sense - it all depends on what visitors expect. We should definitely make sure we conspicuously mark that the links will open in a new tab, so visitors aren't surprised when their back button doesn't work.

**Comment by CloudNiner** [comment]
This is referring to the dataset links in the Lab legend
