### ISSUE TITLE
Group Indicators in sidebar by Temperature/Precip

### ISSUE THREAD

**Issue by CloudNiner** [azavea/climate-change-lab#44]
![cclab-sidebar-groups](https://cloud.githubusercontent.com/assets/1818302/18314893/022dbcec-74e3-11e6-9187-9cfb58da7d37.png)

**Comment by flibbertigibbet** [comment]
Categories do not exist currently in indicator API response. Make an issue against that repo?

**Comment by CloudNiner** [comment]
Seems like a frontend concern to me? We return the variables each indicator uses, so we could just filter tasmax/tasmin to the 'Temperature' category and pr to the 'Precipitation' category.

**Comment by flibbertigibbet** [comment]
Sure, that works.
