### ISSUE TITLE
Add authentication for API

### ISSUE THREAD

**Issue by CloudNiner** [azavea/climate-change-lab#5]
Some options:
- Use API login, CORS, cookies
- Setup account in lab

**Comment by flibbertigibbet** [comment]
azavea/climate-change-api#60 adds CORS support to server side

**Comment by flibbertigibbet** [comment]
Angular 2 does not have interceptors, so there is not a straightforward way to add authentication credentials to all API requests as we have done in Angular 1 projects previously. See [this discussion](http://stackoverflow.com/questions/34464108/angular2-set-headers-for-every-request).

**Comment by CloudNiner** [comment]
Interesting discussion. A wrapper http service for interacting with the climate API is probably the way to go here. Would be useful to break out to a separate library down the road for reusability.

**Comment by CloudNiner** [comment]
Closed by #50 and #41
