### ISSUE TITLE
Graph control toggles don't persist on graph update

### ISSUE THREAD

**Issue by fungjj92** [azavea/climate-change-lab#69]
Feature being on/off is maintained but the toggle default resets to off if models, scenario, or city change.

<img width="542" alt="screen shot 2016-09-16 at 11 13 37 am" src="https://cloud.githubusercontent.com/assets/10568752/18590938/a23a30a4-7bfe-11e6-9c7d-7c4d6548b828.png">

**Comment by CloudNiner** [comment]
Closed by #70 and #72
