### ISSUE TITLE
Add globals to webpack build to fix linter errors

### ISSUE THREAD

**Issue by CloudNiner** [azavea/climate-change-lab#8]
App linter currently throws these errors:
```
[default] climate-change-lab/src/ccl/charts/line-graph.component.ts:66:26 
    Cannot find name '_'.
[default] climate-change-lab/src/ccl/charts/line-graph.component.ts:66:38 
    Cannot find name '_'.
[default] climate-change-lab/src/ccl/charts/line-graph.component.ts:69:5 
    Cannot find name '_'.
[default] climate-change-lab/src/ccl/charts/line-graph.component.ts:71:18 
    Cannot find name '_'.
[default] climate-change-lab/src/ccl/charts/line-graph.component.ts:79:30 
    Property 'width' does not exist on type 'ElementFinder'.
```

**Comment by flibbertigibbet** [comment]
The missing underscore reference was easy to fix with an import statement, however the last warning (`Property 'width' does not exist on type 'ElementFinder'`) seems to be related to the jQuery typings not being properly recognized. I'm not sure how that should be addressed.

**Comment by flibbertigibbet** [comment]
`typings install jquery` fails to find it in the registry, though it is listed. Tried installing with `typings install dt~jquery --save --global` as recommended (here)[https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-jQuery], which does silence the jquery type warning, but now results in a different error:
```
[default] /projects/climate-change-lab/node_modules/@types/protractor/index.d.ts:1844:13 
    Subsequent variable declarations must have the same type.  Variable '$' must be of type 'JQueryStatic', but here has type 'cssSelectorHelper'.
```

**Comment by flibbertigibbet** [comment]
Created #8 for jQuery typings issue.
