### ISSUE TITLE
Download CSV of indicator chart data when export button clicked

### ISSUE THREAD

**Issue by CloudNiner** [azavea/climate-change-lab#81]

**Comment by hectcastro** [comment]
A slightly naive CSV export feature was recently [added to another project](https://github.com/azavea/pwd-stormdrain-marking/pull/149/files#diff-bb984288935983cae62a1e6917c93b03) that makes use of `StreamingHttpResponse`.

I don't know if it'll be useful here, but in that scenario research was done to determine the feasibility of generating the CSV within the request/response cycle. Something more sophisticated may be needed here (background job, writing to S3, etc.).

**Comment by CloudNiner** [comment]
Thanks for noting this. This particular feature will probably just generate the CSV in the browser since the size of the file is small. Alternatively, we could do something similar to what you suggest, and add a CSV serializer to the Indicator endpoint. But that requires making a second request for the same dataset, against an endpoint that does a significant amount of work.
